### ISSUE TITLE
Error from AppExecutor

### ISSUE THREAD

**Issue by gcampax** [Stanford-Mobisocial-IoT-Lab/thingengine-core#16]
Jun 06 10:24:53 thingpedia thingengine-child-26[647]: TypeError: Cannot read property 'message' of undefined
Jun 06 10:24:53 thingpedia thingengine-child-26[647]: at AppExecutor.get error [as error] (/opt/thingengine/node_modules/thingengine-core/lib/apps/app_executor.js:88:32)
Jun 06 10:24:53 thingpedia thingengine-child-26[647]: at RpcStub.events.EventEmitter.RpcStub.get (/opt/thingengine/node_modules/transparent-rpc/rpc_socket.js:321:23)
Jun 06 10:24:53 thingpedia thingengine-child-26[647]: at RpcSocket.<anonymous> (/opt/thingengine/node_modules/transparent-rpc/rpc_socket.js:212:29)
Jun 06 10:24:53 thingpedia thingengine-child-26[647]: at Promise.apply (/opt/thingengine/node_modules/transparent-rpc/node_modules/q/q.js:1165:26)
Jun 06 10:24:53 thingpedia thingengine-child-26[647]: at Promise.promise.promiseDispatch (/opt/thingengine/node_modules/transparent-rpc/node_modules/q/q.js:788:41)
Jun 06 10:24:53 thingpedia thingengine-child-26[647]: at /opt/thingengine/node_modules/transparent-rpc/node_modules/q/q.js:1391:14
Jun 06 10:24:53 thingpedia thingengine-child-26[647]: at runSingle (/opt/thingengine/node_modules/transparent-rpc/node_modules/q/q.js:137:13)
Jun 06 10:24:53 thingpedia thingengine-child-26[647]: at flush (/opt/thingengine/node_modules/transparent-rpc/node_modules/q/q.js:125:13)
Jun 06 10:24:53 thingpedia thingengine-child-26[647]: at _combinedTickCallback (internal/process/next_tick.js:131:7)
Jun 06 10:24:53 thingpedia thingengine-child-26[647]: at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by gcampax** [comment]
Fixed by 3d8a9d57f86d82806be1010efcb1faa088db97e1
